# -*- coding: utf-8 -*-
import pandas as pd
import numpy as np
import pandas_ta as ta

# Auto-generated by StrategyEvolver v22 (deterministic, no LLM)
# Optimisation note: No improvement found after tournament. Keeping current params, incrementing version.

PARAMS = {
    "atr_period": 14,
    "fvg_atr_multi": 0.55,
    "sl_atr_multi": 2.0,
    "tp_atr_multi": 5.0,
    "trail_atr_multi": 2.0,
    "sma_fast_period": 20,
    "sma_slow_period": 50,
    "cmf_period": 20,
    "cmf_threshold": 0.05
}


def analyze_chart(df):
    """
    Inputs OHLCV DataFrame and appends Smart Money Concepts signals.
    Entry logic: FVG retest with SMA trend filter and CMF volume confirmation.
    Parameters are evolved automatically — logic is fixed.
    """
    required = ["Open", "High", "Low", "Close", "Volume"]
    if not all(c in df.columns for c in required):
        raise ValueError(f"DataFrame must contain {required}")

    p = PARAMS

    # 1. Trend filter: dual SMA
    df["SMA_FAST"] = ta.sma(df["Close"], length=p["sma_fast_period"])
    df["SMA_SLOW"] = ta.sma(df["Close"], length=p["sma_slow_period"])

    # 2. Volume confirmation: Chaikin Money Flow
    df["CMF"] = ta.cmf(df["High"], df["Low"], df["Close"], df["Volume"],
                       length=p["cmf_period"])

    # 3. Volatility baseline: ATR
    df["ATR"] = ta.atr(df["High"], df["Low"], df["Close"], length=p["atr_period"])

    # 4. Fair Value Gap detection
    #    Bullish FVG: Low[t] > High[t-2]  — price leaves an upward gap
    #    Bearish FVG: High[t] < Low[t-2]  — price leaves a downward gap
    df["bull_fvg_size_raw"] = df["Low"] - df["High"].shift(2)
    df["bear_fvg_size_raw"] = df["Low"].shift(2) - df["High"]

    min_fvg_size = p["fvg_atr_multi"] * df["ATR"]
    df["bull_fvg_active"] = (
        (df["Low"] > df["High"].shift(2)) &
        (df["bull_fvg_size_raw"] >= min_fvg_size)
    )
    df["bear_fvg_active"] = (
        (df["High"] < df["Low"].shift(2)) &
        (df["bear_fvg_size_raw"] >= min_fvg_size)
    )

    # Capture FVG boundaries at creation for retest checks
    df["fvg_bull_upper"] = df["High"].shift(2)   # upper edge of bullish void
    df["fvg_bull_lower"] = df["Low"]             # lower edge of bullish void
    df["fvg_bear_upper"] = df["High"]            # upper edge of bearish void
    df["fvg_bear_lower"] = df["Low"].shift(2)    # lower edge of bearish void

    df["signal"] = 0

    # 5. Long signal: retest of prior bullish FVG with trend + volume confirmation
    long_cond = (
        df["bull_fvg_active"].shift(1).fillna(False) &                    # FVG formed last bar
        (df["Low"] <= df["fvg_bull_lower"].shift(1)).fillna(False) &       # price retraces into gap
        (df["Close"] > df["fvg_bull_lower"].shift(1)).fillna(False) &      # bounces: close above lower edge
        (df["SMA_FAST"] > df["SMA_SLOW"]).fillna(False) &                  # uptrend confirmed
        (df["CMF"] > p["cmf_threshold"]).fillna(False)                     # buying volume present
    )
    df.loc[long_cond, "signal"] = 1

    # 6. Short signal: retest of prior bearish FVG with trend + volume confirmation
    short_cond = (
        df["bear_fvg_active"].shift(1).fillna(False) &
        (df["High"] >= df["fvg_bear_upper"].shift(1)).fillna(False) &
        (df["Close"] < df["fvg_bear_upper"].shift(1)).fillna(False) &
        (df["SMA_FAST"] < df["SMA_SLOW"]).fillna(False) &
        (df["CMF"] < -p["cmf_threshold"]).fillna(False)
    )
    df.loc[short_cond, "signal"] = -1

    return df
